# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CheminPlusCourt
                                 A QGIS plugin
 Sélection du chemin le plus court entre 2 linéaires
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-23
        copyright            : (C) 2024 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CheminPlusCourt class from file CheminPlusCourt.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .chemin_plus_court import CheminPlusCourt
    return CheminPlusCourt(iface)
