# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CheminPlusCourt
                                 A QGIS plugin
 Sélection du chemin le plus court entre 2 linéaires
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-23
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.core import QgsWkbTypes
from .algocheminpluscourt import *

class CheminPlusCourt:
    def __init__(self, iface):
        self.cheminpluscourt = None
        self.layer = None
        self.iface = iface

    def initGui(self):
        pass

    def unload(self):
        pass

    def run(self):
        # test si un projet est chargé
        projet = QgsProject.instance()
        if len(projet.mapLayers()) <= 0:
            QMessageBox.warning(self.iface.mainWindow(),"Attention","veuillez charger un projet",QMessageBox.Ok)
            return
        self.layer = self.iface.activeLayer()
        if not self.layer:
            return

        if not isinstance(self.layer, QgsVectorLayer):
            return
        else:
            geom_type = self.layer.wkbType()
            geom_type_str = QgsWkbTypes.displayString(geom_type)
            if (geom_type_str == "LineString"
                    or geom_type_str == "LineStringZ"
                    or geom_type_str == "LineStringZM"
                    or geom_type_str == "MultiLineString"
                    or geom_type_str == "MultiLineStringZ"
                    or geom_type_str == "MultiLineStringZM"):
                pass
            else:
                return
        self.cheminpluscourt = cheminpluscourt(self.iface, self.layer)

        if self.layer.selectedFeatureCount() == 2:
            self.cheminpluscourt.cheminpluscourt()
            self.iface.actionZoomToSelected().trigger()



