name: Release QGIS Plugin

on:
  push:
    tags:
      - 'version_finale'

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete previous release if exists
        run: |
          gh release delete version_finale --yes || echo "No previous release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install zip
        run: sudo apt-get install zip -y

      - name: Build plugin zip
        run: |
          mkdir -p IGN_chemin_le_plus_court
          rsync -av --progress . IGN_chemin_le_plus_court/ \
            --exclude .git \
            --exclude .github \
            --exclude IGN_chemin_le_plus_court
          zip -r IGN_chemin_le_plus_court.zip IGN_chemin_le_plus_court

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "IGN_chemin_le_plus_court.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}